# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
arr = np.array([12, 5, 8, 3, 10])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sorted_arr = np.sort(arr)

print("Sıralanmış array:", sorted_arr)

Sıralanmış array: [ 3  5  8 10 12]


# Problem 2

In [7]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 31, 5)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.random.uniform(-1, 1, 10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris9 = np.random.randint(10, 51, (3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplamlari = matris9.sum(axis=1)
sutun_toplamlari = matris9.sum(axis=0)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
# 11- Matrisin en büyük, en küçük ve ortalama değeri
en_buyuk = matris9.max()
en_kucuk = matris9.min()
ortalama = matris9.mean()


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_indeks = np.argmax(matris9)
en_buyuk_indeks_2d = np.unravel_index(en_buyuk_indeks, matris9.shape)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi = np.arange(10, 21)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
ilk_uc = dizi[:3]

# 15- Üretilen matrisin ilk satırını seçiniz.
tersten = dizi[::-1]

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
matris = np.random.randint(10, 51, (3, 5))
eleman_2_3 = matris[1, 2]

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_satir = matris[0]
ilk_sutun_elemanlari = matris[:, 0]

# 18- Üretilen matrisin her bir elemanının karesini alınız.
karesi = matris ** 2

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
yeni_matris = np.random.randint(-50, 51, (5, 5))
pozitif_ciftler = yeni_matris[(yeni_matris > 0) & (yeni_matris % 2 == 0)]

print("Dizi:", dizi)
print("İlk 3 Eleman:", ilk_uc)
print("Ters:", tersten)
print("Matris:\n", matris)
print("İlk Satır:", ilk_satir)
print("2. Satır 3. Sütun:", eleman_2_3)
print("İlk Sütun Elemanları:", ilk_sutun_elemanlari)
print("Karesi:\n", karesi)
print("Yeni Matris:\n", yeni_matris)
print("Pozitif Çift Sayılar:", pozitif_ciftler)

Dizi: [10 11 12 13 14 15 16 17 18 19 20]
İlk 3 Eleman: [10 11 12]
Ters: [20 19 18 17 16 15 14 13 12 11 10]
Matris:
 [[44 42 22 24 29]
 [46 18 15 22 38]
 [17 35 16 14 33]]
İlk Satır: [44 42 22 24 29]
2. Satır 3. Sütun: 15
İlk Sütun Elemanları: [44 46 17]
Karesi:
 [[1936 1764  484  576  841]
 [2116  324  225  484 1444]
 [ 289 1225  256  196 1089]]
Yeni Matris:
 [[ 35  15  50  28   6]
 [-32 -49  24  46  45]
 [ 33  26  28  -9  -2]
 [ 46  -8 -17 -27  41]
 [-41 -27 -48 -28   1]]
Pozitif Çift Sayılar: [50 28  6 24 46 26 28 46]
